import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import Conf from "conf";
import { log } from "./logger.js";

export const PROJECT_CONFIG_FILE = "laststate.yaml";
export const GLOBAL_STORE_OPTS = { projectName: "laststate-cli" } as const;

export interface ProjectConfig {
  project?: string;
  target?: string;
  lep_version?: number;
  trace_url?: string;
  relay_url?: string;
  ingest_token?: string;
  storage?: string;
  [k: string]: unknown;
}

export const SUPPORTED_TARGETS = [
  "esp32",
  "cortex-m",
  "riscv",
  "riscv64",
  "zephyr",
  "arduino",
  "host",
] as const;

export type Target = (typeof SUPPORTED_TARGETS)[number];

let globalStore: Conf<Record<string, unknown>> | null = null;

export function getGlobalStore(): Conf<Record<string, unknown>> {
  if (!globalStore) {
    globalStore = new Conf({ projectName: "laststate-cli" });
  }
  return globalStore;
}

export function findProjectRoot(start = process.cwd()): string | null {
  let dir = resolve(start);
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, PROJECT_CONFIG_FILE))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // also accept cwd itself
  return existsSync(join(process.cwd(), PROJECT_CONFIG_FILE)) ? process.cwd() : null;
}

export function loadProjectConfig(cwd = process.cwd()): ProjectConfig | null {
  const root = findProjectRoot(cwd);
  const file = root ? join(root, PROJECT_CONFIG_FILE) : join(cwd, PROJECT_CONFIG_FILE);
  if (!existsSync(file)) return null;
  try {
    const text = readFileSync(file, "utf8");
    return (parseYaml(text) ?? {}) as ProjectConfig;
  } catch (e) {
    log.warn(`Failed to read ${PROJECT_CONFIG_FILE}: ${(e as Error).message}`);
    return null;
  }
}

export function saveProjectConfig(cfg: ProjectConfig, cwd = process.cwd()): string {
  const file = join(cwd, PROJECT_CONFIG_FILE);
  const text =
    `# LastState config - generated by 'laststate init'\n` + stringifyYaml(cfg);
  writeFileSync(file, text);
  return file;
}

export function mergeProjectConfig(patch: ProjectConfig, cwd = process.cwd()): ProjectConfig {
  const cur = loadProjectConfig(cwd) ?? {};
  const next = { ...cur, ...patch };
  saveProjectConfig(next, findProjectRoot(cwd) ?? cwd);
  return next;
}

/** Precedence: flag > env > project yaml > global conf > fallback */
export function resolveValue(
  key: string,
  opts: { flag?: string; envNames?: string[]; project?: ProjectConfig; fallback?: string } = {},
): string | undefined {
  if (opts.flag !== undefined && opts.flag !== "") return opts.flag;
  for (const e of opts.envNames ?? []) {
    const v = process.env[e];
    if (v) return v;
  }
  const p = opts.project?.[key];
  if (typeof p === "string" && p !== "") return p;
  if (typeof p === "number") return String(p);
  const g = getGlobalStore().get(key);
  if (typeof g === "string" && g !== "") return g as string;
  return opts.fallback;
}

export function maskSecret(v: string | undefined): string {
  if (!v) return "(not set)";
  if (v.startsWith("env:")) return v;
  if (v.length <= 8) return "***";
  return `${v.slice(0, 4)}***${v.slice(-3)}`;
}

export function isEnvRef(v: string | undefined): boolean {
  return !!v && v.startsWith("env:");
}
