import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { PROJECT_CONFIG_FILE, getGlobalStore, maskSecret } from "../lib/config-store.js";
import { generateSecrets, preflight, loadEnvFile } from "../lib/env-manager.js";
import { emitJson, isJson, log } from "../lib/logger.js";
import { header } from "../ui/banner.js";
import { printTable } from "../ui/table.js";

const KNOWN_KEYS = new Set([
  "project", "target", "lep_version", "trace_url", "relay_url", "ingest_token", "storage",
  "POSTGRES_PASSWORD", "TRACE_BOOTSTRAP_TOKEN", "TRACE_JWT_SECRET", "TRACE_SECRETS_KEY",
  "LASTSTATE_INGEST_TOKEN", "LASTSTATE_ADMIN_TOKEN", "LASTSTATE_COMPANY_TOKEN",
]);

function readYaml(): Record<string, unknown> {
  const p = resolve(process.cwd(), PROJECT_CONFIG_FILE);
  if (!existsSync(p)) return {};
  try {
    return (parseYaml(readFileSync(p, "utf8")) ?? {}) as Record<string, unknown>;
  } catch {
    return {};
  }
}

export async function configList() {
  const yaml = readYaml();
  const env = loadEnvFile();
  const store = getGlobalStore();
  if (isJson()) {
    const masked: Record<string, string> = {};
    for (const [k, v] of Object.entries(yaml)) masked[k] = /token|secret|password/i.test(k) ? maskSecret(String(v)) : String(v);
    emitJson({ project: yaml, env_keys: Object.keys(env), global: store.store });
    return;
  }
  header(`${PROJECT_CONFIG_FILE} + .env + global`);
  if (Object.keys(yaml).length === 0) {
    log.warn(`No ${PROJECT_CONFIG_FILE} found. Run 'laststate init' first.`);
  } else {
    printTable(["key", "value"], Object.entries(yaml).map(([k, v]) => [k, /token|secret|password/i.test(k) ? maskSecret(String(v)) : String(v)]));
  }
  if (Object.keys(env).length > 0) {
    console.log("");
    log.info(`.env (${Object.keys(env).length} keys):`);
    printTable(["key", "value"], Object.entries(env).slice(0, 30).map(([k, v]) => [k, /token|secret|password|key/i.test(k) ? maskSecret(v) : v]));
  }
  console.log("");
  log.dim(`global store: ${store.path}`);
}

export async function configGet(key: string) {
  const yaml = readYaml();
  if (key in yaml) {
    const v = String(yaml[key]);
    if (isJson()) emitJson({ key, value: v, source: PROJECT_CONFIG_FILE });
    else console.log(/token|secret|password/i.test(key) ? maskSecret(v) : v);
    return;
  }
  const env = loadEnvFile();
  if (key in env) {
    if (isJson()) emitJson({ key, value: maskSecret(env[key]), source: ".env" });
    else console.log(maskSecret(env[key]));
    return;
  }
  const g = getGlobalStore().get(key);
  if (g !== undefined) {
    if (isJson()) emitJson({ key, value: g, source: "global" });
    else console.log(String(g));
    return;
  }
  const msg = `(key '${key}' not set)`;
  if (isJson()) emitJson({ key, value: null, note: msg });
  else console.log(msg);
}

export async function configSet(key: string, value: string) {
  if (!KNOWN_KEYS.has(key) && !/^[A-Z_]+$/.test(key) && !/^[a-z_]+$/.test(key)) {
    log.warn(`Unknown key '${key}' — saving anyway.`);
  }
  // .env-style keys go to laststate.yaml too (single source) unless .env exists and key is upper
  const p = resolve(process.cwd(), PROJECT_CONFIG_FILE);
  const cur = readYaml();
  cur[key] = value;
  const text = `# LastState config - generated by 'laststate init'\n` + stringifyYaml(cur);
  if (!existsSync(p)) {
    log.warn(`No ${PROJECT_CONFIG_FILE} — creating one.`);
  }
  writeFileSync(p, text);
  if (isJson()) emitJson({ ok: true, key, source: PROJECT_CONFIG_FILE });
  else log.ok(`Set ${key}=${/token|secret|password/i.test(key) ? maskSecret(value) : value} in ${PROJECT_CONFIG_FILE}`);
}

export async function configPaths() {
  const info = {
    project: resolve(process.cwd(), PROJECT_CONFIG_FILE),
    env: resolve(process.cwd(), ".env"),
    global: getGlobalStore().path,
  };
  if (isJson()) emitJson(info);
  else {
    header("Config paths");
    printTable(["scope", "path"], [["project", info.project], ["env", info.env], ["global", info.global]]);
    console.log("");
  }
}

export async function configGenerateSecrets(opts: { onlyMissing?: boolean; envPath?: string }) {
  const results = generateSecrets(opts);
  const gen = results.filter((r) => r.action === "generated").length;
  if (isJson()) {
    emitJson({ ok: true, generated: gen, results });
  } else {
    header("Secrets");
    log.ok(`${gen} secret(s) generated into ${opts.envPath ?? ".env"} (mode 0600)`);
    for (const r of results.filter((r) => r.action === "generated")) log.dim(`  generated ${r.key}`);
    console.log("");
  }
}

export async function configPreflight(opts: { env?: string; deployEnv?: string }) {
  const issues = preflight({ deployEnv: opts.deployEnv });
  if (isJson()) {
    emitJson({ ok: issues.length === 0, issues });
  } else {
    header("Preflight");
    if (issues.length === 0) {
      log.ok("No placeholder/weak secrets detected.");
    } else {
      printTable(["key", "problem", "hint"], issues.map((i) => [i.key, i.problem, i.hint]));
      process.exitCode = 1;
    }
    console.log("");
  }
}

/** Legacy shim: config(action, key, value) */
export async function config(action: string, key?: string, value?: string) {
  const args = [action, key, value].filter(Boolean) as string[];
  const sub = args[0];
  if (!sub || sub === "list") return configList();
  if (sub === "get") {
    if (!args[1]) { log.err("Usage: laststate config get <key>"); process.exitCode = 1; return; }
    return configGet(args[1]);
  }
  if (sub === "set") {
    if (!args[1] || args[2] === undefined) { log.err("Usage: laststate config set <key> <value>"); process.exitCode = 1; return; }
    return configSet(args[1], args[2]);
  }
  if (sub === "paths") return configPaths();
  if (sub === "generate-secrets") return configGenerateSecrets({ onlyMissing: true });
  if (sub === "preflight") return configPreflight({});
  log.err(`Unknown config subcommand: ${sub}. Use: list | get <key> | set <key> <value> | paths | generate-secrets | preflight`);
  process.exitCode = 1;
}
