import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

function ensureGitRepo(dir: string): void {
  // Best-effort `git init`: skip when already inside a repo; never fail `init`.
  try {
    execFileSync("git", ["rev-parse", "--is-inside-work-tree"], { cwd: dir, stdio: "ignore" });
    return;
  } catch {
    // Not a repo — fall through to init.
  }
  try {
    execFileSync("git", ["init"], { cwd: dir, stdio: "ignore" });
    console.log(`  Git repo initialized in ${dir}`);
  } catch {
    console.log("  Skipped git init (git not available)");
  }
}

export async function init(opts: { projectName?: string; target?: string; git?: boolean }) {
  const name = opts.projectName ?? "MyLastStateProject";
  const target = opts.target ?? "cortex-m";
  console.log(`\n  Initializing LastState project: ${name} (target: ${target})\n`);

  // Fresh random dev token per project — never reuse the old hardcoded one.
  const devToken = `dev-${randomBytes(9).toString("hex")}`;
  const configContent = `# LastState config - generated by 'laststate init'
project: ${name}
target: ${target}
lep_version: 2
trace_url: http://localhost:8080
ingest_token: ${devToken} # local dev only — rotate before any shared use
`;

  const cmakeSnippet = `add_subdirectory(third_party/latch)
target_link_libraries(\${PROJECT_NAME} PRIVATE laststate::latch)
`;

  const cSnippet = `#include <latch/latch.h>

void app_init(void) {
    ls_identity_t id = {
        .device_id = "${name.toLowerCase().replace(/\s+/g, "-")}-001",
        .firmware_version = "v1.0.0",
        .build_id = "dev-build"
    };
    ls_init_with_identity(&id, NULL);
    ls_boot();
    ls_breadcrumb("app:init");
}
`;

  if (!existsSync(name) && name !== "MyLastStateProject") {
    try {
      mkdirSync(name, { recursive: true });
      writeFileSync(join(name, "laststate.yaml"), configContent);
      writeFileSync(join(name, "latch-snippet.c"), cSnippet);
      console.log(`  Created ./${name}/laststate.yaml`);
      console.log(`  Created ./${name}/latch-snippet.c`);
    } catch {
      // fallback to cwd
      writeFileSync("laststate.yaml", configContent);
      console.log("  Created ./laststate.yaml");
    }
  } else {
    writeFileSync("laststate.yaml", configContent);
    console.log("  Created ./laststate.yaml");
  }
  if (opts.git !== false) {
    try {
      ensureGitRepo(existsSync(name) ? name : process.cwd());
    } catch {
      // never fail init on git errors
    }
  }
  console.log(`\n  CMake snippet:\n  ${cmakeSnippet}`);
  console.log("  Next: add #include <latch/latch.h> and run 'laststate test'\n");
}
